version: 2.1
jobs:
  build-test:
    working_directory: /verum
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-test-{{ .Branch }}
          paths:
            - /caches/verum.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/verum.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build -t $DOCKER_USERNAME/verum-test:circle-$CIRCLE_SHA1 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/verum.tar $DOCKER_USERNAME/verum-test:circle-$CIRCLE_SHA1
      - save_cache:
          key: v1-test-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/verum.tar
      - run:
          name: Run test
          command: |
            docker run -e CODECOV_TOKEN=$CODECOV_TOKEN --rm $DOCKER_USERNAME/verum-test:circle-$CIRCLE_SHA1
  build-deploy:
    working_directory: /verum
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-deploy-{{ .Branch }}
          paths:
            - /caches/verum.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/verum.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build -f Dockerfile.conan -t $DOCKER_USERNAME/verum-deploy:circle-$CIRCLE_SHA1 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/verum.tar $DOCKER_USERNAME/verum-deploy:circle-$CIRCLE_SHA1
      - save_cache:
          key: v1-deploy-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/verum.tar
      - run:
          name: Run deployment
          command: |
            docker run -e CONAN_PWD=$CONAN_PWD -e CONAN_USR=$CONAN_USR --rm $DOCKER_USERNAME/verum-deploy:circle-$CIRCLE_SHA1

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-verum-workflow:
    jobs:
      - build-test
